name: Build and Release
run-name: build-release-${{ inputs.tag_name }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
        description: "The tag name to release"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --dev

      - name: Build the project
        run: python -m nuitka --onefile --onefile-no-compression --assume-yes-for-downloads --windows-console-mode=disable --output-dir=build --output-filename="geometry-game_${{ inputs.tag_name }}.exe" ./geometry_game/main.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.tag_name }}
          files: build/geometry-game_${{ inputs.tag_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
